### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by deelanM** [BearStudio/start-ui#3]
**Description**

Password reset feature

**Task list**

- [x] `PageResetPasswordRequest` : renders a form with title `Reset your password` and a single input labelled `Email`. The form's submit button makes a call to `useResetPasswordInit` custom hook.

- [x] `account/service` : create `useResetPasswordInit`, which returns a `useMutation` call to endpoint `/account/reset-password/init`, with email as payload.

- [x] `PageResetPasswordFinish`: renders a 2-input form with title `Reset password`. The first input labelled `New password`, the second `Confirm new password`. The form's submit button makes a call to `useResetPasswordFinish` custom hook. Add `Formiz` validations to ensure both inputs' value are similar.

- [x] `account/service` : create `useResetPasswordFinish`, which returns a `useMutation` call to endpoint `/account/reset-password/init`, with reset key and password as payload.

- [x] use toast hooks (`useToastError` and `useToastSuccess`) to indicate success and fail case accordingly

**Comment by ivan-dalmet** [comment]
The Reset Password is not the same as Change Password ;)

Reset password routes are already available in app/account/Routes
```jsx
<RoutePublicOnly
        exact
        path={`${path}/reset`}
        render={() => <PageResetPasswordRequest />}
      />
      <RoutePublicOnly
        exact
        path={`${path}/reset/confirm/:resetKey`}
        render={() => <PageResetPasswordConfirm />}
      />
```

The use case is when the user is NOT logged and he/she forgot his/her password ;)

**Comment by deelanM** [comment]
> 
> 
> The Reset Password is not the same as Change Password ;)
> 
> Reset password routes are already available in app/account/Routes
> 
> ```js-jsx
> <RoutePublicOnly
>         exact
>         path={`${path}/reset`}
>         render={() => <PageResetPasswordRequest />}
>       />
>       <RoutePublicOnly
>         exact
>         path={`${path}/reset/confirm/:resetKey`}
>         render={() => <PageResetPasswordConfirm />}
>       />
> ```
> 
> The use case is when the user is NOT logged and he/she forgot his/her password ;)

I misunderstood the use case. I've updated the description accordingly.
