### ISSUE TITLE
🚧  API JHipster mapping

### ISSUE THREAD

**Issue by medamineziraoui** [BearStudio/start-ui#9]
## Account Resource
- [ ] `GET  ​/api​/account`
- [ ] `POST  ​/api​/account`
- [ ] `POST  ​/api​/account​/change-password` https://github.com/BearStudio/start-ui/issues/3
- [ ] `POST  ​/api​/account​/reset-password​/finish` https://github.com/BearStudio/start-ui/issues/3
- [ ] `POST ​/api​/account​/reset-password​/init` https://github.com/BearStudio/start-ui/issues/3
- [ ] `GET  ​/api​/activate`
- [ ] `GET ​/api​/authenticate`
- [x] `POST /api​/register`

##  user jwt case
- [x] `POST ​/api​/authenticate`

## User resource
- [x] `GET ​/api​/users`
- [ ] `PUT ​/api​/users`
- [ ] `POST /api​/users`
- [ ] `GET ​/api​/users​/authorities`
- [ ] `GET ​/api​/users​/{login}`
- [ ] `DELETE /api​/users​/{login}`
